spring:
  application:
    name: microservice-discovery-eureka-ha
---
# 连字符(---)将该application.yml文件分为三段，
#第二，三段分别为spring.properties指定了一个值，
#该值表示它所在的那段内容应用在哪个Profile里。
#第一段由于未指定spring.profiles,因此这段内容会对所有Profile生效。
spring:
  profiles: peer1
#  指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
#    指定当profile=peer1时，主机名为peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
#      将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/