server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
#    microservice-provider-user.ribbon.listOfServers
#    用于为名为microservice-provider-user的Ribbon客户端设置请求的地址列表