server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
#    是否将自己注册到Eureka Server，默认为false
    fetchRegistry: false
#    是否从Eureka Server获取组测信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，
#默认为http://localhost:8761/eureka;多个地址之间可使用，分隔。