security:
  basic:
    enabled: true
#    开启基于HTTP basic的认证
  user:
    name: user
    password: password123
#    配置用户名密码
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
#    是否将自己注册到Eureka Server，默认为false
    fetchRegistry: false
#    是否从Eureka Server获取组测信息，默认为true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
#将eureka.client.serviceUrl.defaultZone修改为
#http://user:password123@EUREKA_HOST:EUREKA_PORT/eureka/的形式
